Evolucionar la capacidad de enmascaramiento de datos
bancolombia/data-mask pull request #20
Opened 2024-05-28 16:01 UTC by JEZAPAT

Se requiere evolucionar la capacidad de enmascaramiento de datos que hoy en día se ofrece con el objetivo de que sea dinámica.

Actualmente, solo se permite enmascarar parte del string al principio, al final o en medio, no por palabra como lo requiere el negocio.

Ejemplo de como funciona actualmente: "Seb*** ****** *****"

Ejemplo de como se espera el nuevo funcionamiento: "Seb**** Cue*** Nav***"

Se agregaron dos propiedades opcionales al enmascaramiento las cuales habilitan el enmascaramiento múltiple generando el resultado esperado, las cuales son isMultiMask y separator.
**isMultiMask** es una bandera con la que se habilita la funcionalidad 
**separator** es un string con el cual se puede definir el carácter por el cual se va a separar el campo ingresado.

Al  momento de dividir el campo a enmascarar por medio del **separator** se reutiliza la funcionalidad que existía para no afectar el comportamiento actual del código.

**Se hicieron pruebas implementando la libreria en el Distribution Router.**

2024-05-28 16:32 UTC, gabheadz requested changes
Please use conventional commits https://www.conventionalcommits.org/en/v1.0.0/ to describe changes made in the commits.

2024-05-28 16:32 UTC, gabheadz commented on gradle.properties
> +version=1.3.0
this project uses semantic releases, so there´s no need to increase manually the version spec. Please undo this change.

2024-05-29 15:00 UTC, JEZAPAT commented
> Please use conventional commits https://www.conventionalcommits.org/en/v1.0.0/ to describe changes made in the commits.

done

2024-05-30 11:46 UTC, gabheadz approved these changes
Thanks for your contribution!

2024-05-30 11:46 UTC, merged